[[Clang]]
arch = "x86_64"
git-tree-sha1 = "303e77a7766ea8616b5abe32251fcbecc131379d"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "01b0faee1f13a49f1625bdc9684141cfc4899a46788964fcf50b8919cdc0cd2d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "b3e48b142964d5b8dd04d09d9d0b1fc243d7413c"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "35075581c6c0a1410f5c8c83b75ae8394310b2811575b62260e2c55fab257a42"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "85c69b331427c72575c02ac39d9650ddf54a67fa"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "5d5f68f0a9d69b7189c01e15401d4bb718f99586f7dfd442ae2c010f5a184e83"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bb4646b4457754a49e8e75054b9014384a83d78"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "b9db39e141e12194bd794adcd20c4f15d8797804c154580933b729654d57a32b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang]]
arch = "powerpc64le"
git-tree-sha1 = "b3d99ce362452f1ec709a09d89be7279e7f3d880"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "39cbf825459e7ac505197a1bd649430ad27503810564edaa5dbc9f7aac8b235d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "b47fc96af74076a20f6fd8ff9c283ed122e3f1d0"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "19dfafa2f5abf3709eda7ac0b64008941433074e82db13c16b88a4956fdcc8d5"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "a185da36e829a66a2f0b62f77736af359f319a91"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "c7d74bd38ae3e862931ebad4a4cb81f372899091ea5fd73801e9b5c48edccce1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "4e1a415983ec031b053e98c3ac8a9e7775d594f4"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "20d882d1378f6f339d5f01f6d55de25264814637bad20994b16bfaa4378241df"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02ae7be7b5e15e4fe1b51c54f3d41c39f29584fa"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "5590d0c3bb392b716148662b0f061ae141708e0d1d81578090138de85ba78cfb"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2bcc58e2f10b42b254e9deefc4f9bf220c66ef3"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "dfc46d800d7154994e3bd9308618eec065df795a3644f585399aba97b8382f33"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "010e72cd7f169264d9989359dac2aebf93192bd5"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "13829d50feed67aadb8a5434afe097d198d7a0e0ede621a8a99dccf03739d37c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "e38f5cba745e25414fad0b15df836c263efb0b67"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "ef49ce8364e51a1cff5ada95c4a18398080b3b730bc952abfe44b624ef62b18c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "e2592fff4a9dd53538915aea4fbbc72855e34297"
os = "macos"
os_version = "14"
target = "any"

    [[Clang.download]]
    sha256 = "bc38dd55668430c1e27970ff0143d15f7621554209cfc46616aba7527126f640"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "322349404b41d24f9288677d90c07e6e51d7acf8"
os = "macos"
os_version = "20"
target = "any"

    [[Clang.download]]
    sha256 = "aa82425ce12a561701f77a26e0ba844e88e051c106320fff3331d6a02cb16b89"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "dc1c95ef386f75022f88dfdc655c01463c43e35f"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "7400459ba12244c126a2d4270ca163542e064a60d92bd96da212b97be9ae05d2"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "67fa6289bae75d2e6e07b56ca171f8a8f1b529fd"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d7ab4976a5cf9f08a9fe786bc4f6e98f07f22a0df086d8bc0d8ea2bae59f048b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "1484bcafe1ce2238bc1543774d736638d950ae1b"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "f0ecce8c3b73438f5f26cea736516afabb3f4e3756b740b9e3dc9df6da3a2bc5"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b950ce6f9c78d80d4d7e07562914cc39fbcd85d"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "cb14a2f4384bbec5930da22b77ba95ebe3e51dda4647e64549cbd87988ad56cc"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "46079d3056895ddac0aebcd55f3304b39d4fc0b3"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "9533c8d13a109b449e7835e20ba3d7fee5834769b77a923a82b2eadfdc8ac54a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "89afec92cfbda02d971ebcfd95dd32894371864b"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "2f74b0c3bce71522a755554da95d790ee5471c6c0d06985c6ab902e9711039b1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "b26db272a217143174ef320c8e4928ebcdee7bbc"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "744b6d42e8fbecd9a941e8e83d631e4f4ecb2c561ba1e3e0f537063acd8e0bf3"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "6e7689d2d6896b9cc166f7243b607f1887970415"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "8a979fcd6794f3d58a4900f002f46826b749f773bc42a45ab44c6c3ec4d8f479"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "895d5af43f642dafe85ac6dd5df5d5a9d78ce45f"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "92b1c71c235973f6a80b853540a5ebdec8a9e9d98a4dd0999910416fe16c9faf"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "69adce2d8800bc3f10ef3c9447df3982e34832ea"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d5f4f8f5e267f77dbe8880ae5f3ccb2f969cd027e35c93c8e8fc5f37da658d01"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "58f7ce9b27b07410d56099eb30b9255b49baf0b8"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d4fc574e24fb958be6b9eefaaf66465c30455da0666572e4332e532ac0ecb671"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "4db3a07fa3875d4b542e6da33ad71f39c7a9030c"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d0ddf17782eef3cfcc38d16ae252a8d04d577d3d60fdb9c81e6845219a35ad9f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "d9bcf9059383a8d7e81f470c0306388663a39796"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "81d910c06a9671d3873a091d040042984fd1225dabc5057e909f6a978b9cb0b8"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "44a8de0f10d2c759f0e72b04dec8d73b4cd1b094"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "e12b4b8fcd68a99800eee8d0a1ac26d038c5d4c46d5546ad6dce22ac006c50a3"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6ddbfc26f1a07126a884aec84011ef449e3f9e53"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "beb06a11b661e3b05a1335947e4d17f40ccb2201a91fbb34e265b9b9dd23b5f8"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "e6e81d1e47a7c6fde6b95bd60b510e111aef6221"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "cb94cbacc27769598ca5c773154d60ac6d1656dc912c0e6c4de5d1b66a71e0cc"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "ff4aae52b560b622ab54b7dc2bf56d1b0a17860d"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "0fdd5ab4b21396a1840139dbae15944105836ec5966e5c4bc42dfe8b743ace71"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c78520892902d2cf7a615e9eb5051a08e24cddbe"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "531af6db3c84b2aabb5d0816dd996f4cccf1e73889829af7a912dddaf82331ca"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "1ca536cf8253fe720dd26900080d1b385660cf31"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "a75eeac187c8ceeb17d063322df7a5ac960b80cd70141c7bfae9bc92f85c9d5a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "76cda561928e349cc9951954637f303266a1f683"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "b4224d98331ff7cdb771c3d545738d97c94b07fdfa9e5bdf1e3ff3e1e0fb0f19"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "dccd79532179ee7cb0b82e44f3ad4d072ff6e73c"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "1f6106e3aa9c5f76ac946b0722e870ee8e323cb5481576aa84ef71c19834d74b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "701d9083ce3b870cac5ae9b495b97a86049798d9"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "18e940a2d53f2f4a6feef01efb40c154167686d825c5492355a5dd1a25b3b274"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6f3cb4154b304b272552381757310866fb219ce"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "1bdadbca838f19068a9d247a463871cbd1b79ac567de167035222cc44e4a3e7b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b638f582716aab5960e410b8517ff9f0328898d"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "8d0dd3891661f3521250e82e7c4b0e02eca6d02da89611066e0682d9180b6760"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "147be1e89df19bff97e14612decb760e40cd1458"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "d7aee09f0576f99db7ae02091899383b8a94b5990938aaa605a4a8cf31657b9b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "3da04a48c23caa7bd1d28c82278184f8cb575c02"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "9d9ae05b5322162e45041ba2092ba676171000c7ca6cc59a0e81b9ee2de57709"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2d68b805bc3d97561f6eabf573f6f38f9ad7fc10"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "b831feba885e4f529642c235093e31529e72fa74926002cb215bcef3b9cc5a2e"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f9246f93d7d509f4035c8ad4c74765b9ab2a4098"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "df84e7cb1729e4b3c53b6cc6583229cba112485a1c411c76ffa539ae66c14f39"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"
