[[Clang]]
arch = "x86_64"
git-tree-sha1 = "303e77a7766ea8616b5abe32251fcbecc131379d"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "119c5a7db44deed1e4eda7d8ebe6725d695a47a62f022f7445b461bb9f19797d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "b3e48b142964d5b8dd04d09d9d0b1fc243d7413c"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "601aa5a4c1cc400bb1067dca1118d2c19f0653f0fbeecd9bc1f9de9a634d696c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "85c69b331427c72575c02ac39d9650ddf54a67fa"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "6025d84aec8433eeceb33c988f20b8e1924fbf059f96a35de0dcbda78368d66b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bb4646b4457754a49e8e75054b9014384a83d78"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "5ec2f84a5da4c4e6a502be79fca491798d3b0ef442fe52c984e93a60a56f510f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang]]
arch = "powerpc64le"
git-tree-sha1 = "b3d99ce362452f1ec709a09d89be7279e7f3d880"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "0622adcc6dd88262131e3c40ce1ace141fc2f211f830891ed20ceba323fd779f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "b47fc96af74076a20f6fd8ff9c283ed122e3f1d0"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "942abec2dc6a6e810633019052fef47e9c58699412072eca1170d1f9b8015e38"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "a185da36e829a66a2f0b62f77736af359f319a91"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "c035d4fe057f828aa0c97080ef421e575b636483509336c2b2c8742a2078126b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "4e1a415983ec031b053e98c3ac8a9e7775d594f4"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "109b2bb888b11a11f03a857238a5dfbc66480af1398d11f83770637e28f236fe"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02ae7be7b5e15e4fe1b51c54f3d41c39f29584fa"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "b326e4f3755b4eda09609f14b5c784624251217fff1e7f15096a1bed002c46e3"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2bcc58e2f10b42b254e9deefc4f9bf220c66ef3"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "034d02807f9faafefbbd4b9b93a7caca9a50db20a54176fd72c14014eb763884"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "3d496da50dc3632c36ca74a9043e0fb267eca307"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "8c9f94c761a8f40e5316a44e2959e8df1c91150ea58c4c9d7058e9a0055da4cd"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "2c37c99736a663efbdfa5bc1cdeca0049b4f2f46"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "6bf15b9f8f44ddb5a80521796e9583923de38f96967dceebbadabefeec7675f6"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "e2592fff4a9dd53538915aea4fbbc72855e34297"
os = "macos"
os_version = "14"
target = "any"

    [[Clang.download]]
    sha256 = "6ff2c60f43fd14f1b5df5bace76b55f93bf9afd8910e84d71245049a4375aca7"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "322349404b41d24f9288677d90c07e6e51d7acf8"
os = "macos"
os_version = "20"
target = "any"

    [[Clang.download]]
    sha256 = "4931c7fadfa349b44374aa24584d2c56e7b465c56571c8b9b3a0d103774b32e0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "413b5cb9130bb06768d0d4d6286b8a2ccfe67305"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "2af2ddaac989f45f5f3fb762931419bc8e7b4e656e5ef2e7d72531d73105348d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "c1e19e73df216e49b011e56d9d7431fa6c0b7dde"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "50774a370097a83c95b0d4d4be38c9fd75cb76cd29b86c8d447c0b2e2f5acf10"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "9ee6ff551866a94f372c3d25c1e920b0aefc2f86"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "b9dbabc8939c306111975f93f59e503918feaf288f1a440544cc994aa899aa98"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb8c6d6057ef9c2a9f72eaf73c2bb7a7f65b7ed1"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d9f225ee3ed51d8f6dbf6b590464210e40f5481a1327afbc61c62c72f9137b81"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "76c28d36df0f7364159ac564cae84fa42751fd51"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "268d08a89d7a868e86cd753d20f8d47a174cbe61e0e93ac62250ade7a8ac8cdc"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "4a09d005ac6a94e0199dfc36e67df213cf7ac650"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "8f2faf44a641494aa0a03d69bc48d18465210d0751be2c6fcc78a677edaf625f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "6a2c3bff6a78d3b0be6cb4587a31e2e24bd6f46b"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "7c8ae7d0809dc0a846cc4c422e2f7403c6917e6b422bccc96351301bdd5d7b54"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "b8131396cee7ce352b3532a53c286e7e13a07390"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "8094dd0a841a33aede47e3dda12b82323878c2965dbeeaf25cf033381e689ede"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb6eb8247177434466a6d4393d228cc07fb25ea5"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "04d0c752ed05eb77f49d0098e3a1ec08c2ff00f9af4c97f1cb080f423236c97e"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51da7bded5bd33415ebf5826f26d91f7a0af1dc9"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "951b6744e7fdae34783a166105f3d0b41a9ff1fa4dc173b15c0059dea296cf22"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "ff6f641b99470254bcfcbfc46afffcf420f55806"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "ed45ef1ba4caf77d8c93f89776af9b818a755b44608cd4df712c2175f272ba53"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "f3f2a2ae806a8e830997fe2df374974a2b3be336"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "305b13dd81b26a9232d4b63c78ab900d111c449ffd194eba7d742bb01070126b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "a9f6a588f82c37f04cbbd699eae39fab7a44c73b"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "0d0ca107fa5a3816f8af75acd3159d1b575cfa4c311b97701e62a5a5f4f5ebb0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "21a9505cdfb421350a98335cc9fc0aeecd0f49a9"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "c779ed57223377fc63b28b4e9c865f06d8383bf6464e94a198854e2daa763bd0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4990436b3e3fe6780338c85154c2bf4db6a49ceb"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "5decbf9da4068f13fe967c5819203fef93be7fa4efd69a187265c6cbdf650a73"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "964030e7a8528608863164b24e10a4ad7e774821"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "3345e0ff2334bc28c791a2809da23eaf3452d098b63aa1c3507516ed29c3e5e6"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "77405f166898e0c2962f2cbdb687da6eca4359ce"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "48e9c048c11313daace6edb273e7a341da5bc76fff49a8173a69e50deeb7eb5e"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2296438c998277848bd64a513543a8c8ab5892db"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "b10e7fc6a0fd6b7f039baa8adec2ad1e126d10132ea542ed0f56b9da8dd69c9d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "1f7e8dd6890300b405f468adf7a149610ed163b5"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "4c82346931571730bdb7fcbf7348fdba0e2ce42d387629c1f7d596ecdecf7b29"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8f5d7abcbe78390147ee992da64e8178d3347202"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "9de52eec357fafa46ac3c990be86e9005548c8fff369a526107beb5ead1e594b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "b84f39787e5d1ca54ca9fbac6637b373336970ba"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "2d3ce64f92aff3f7fb2fc797f2922604f9aaae2a0ba58d47a7bfa60ba3f45420"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "ad8d35fea0b3d239eca8f6ad9ba4db08f1138945"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "4a045edfdd93cc1f31dc7828d2e684e9beec7359f4487d033984863e6c2db051"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29f18bab924acefb1c7503d979cf7ef8a9edecf1"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "00986742f75b8a84e04f8c0beae046cde463a9ea43b1a6d09c8fbcb6801b4fea"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d641b8aa3d84bf2628a154924ef03008c457250"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "e7ac1b27574d358bcdf36d39a949ba8c99a17756470ff256f9e8184f4c518193"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "46719ec4cd435eb488aca8a78b1c462cf67bc89d"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "193b45ad678a75858caf10bf69fca9fe811872c4e4a26b76bed77a1825082bcf"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "9e6215046d43f6625f43e8105c9dbe043f987190"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "fead7b18799dbe1bb4aba2001cec204d6f4d681d91afe7ce2948154e20c3a654"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "908467b17b6b2341c0fac3902c7ec00ec36c3a60"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "d58247d9fcc61f81c7700cabc1b0e0e65d52933a71da6e93405e7a486fda947e"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "c00dca1e2f430f7fdfd3fced3774cdbcd3ed3c36"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "266b048fe5e6b0077ad39c53f6b4fa0621b2309eca13f756dfdf51e961523ee4"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"
