[[Clang]]
arch = "x86_64"
git-tree-sha1 = "d377cc020de39e671fc8cd3ee8521f49d895ef41"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "db7e92d6ff32d30c487cd034eaa4c1633d71aa20ddb6bd28e7cd34ba0e81585a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7-GCC/Clang-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "63d565f91fbcf094f1d662f2ad16f7eae7ba22d6"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "4d18253bfd9ba34f46acf3ed4c26298469fed282de8a0d2f179fe1cd05e9a43d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7-GCC/Clang-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"

[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "a7c65ccf034c732dd8359db18b61c28198c481dc"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "4f4b81a094ffb32f4466fe03ce92f15b7e2bb768ce09da7e59df6640f21cd2f5"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7-GCC/Clang-build_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "d1935c5ce8c784ab318584c9dad2318386cb88d2"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "c95f51ab8c4da9fdaf4662fa85c4e393531ec04d7891584e466ca6ecb5efc3f4"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7-GCC/Clang-build_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"

[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "50525856ffa42d2c58903a31121a7ebc0615871a"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "f9b5613df6d53afa7d70af378d81e11186e873bb7b5ecfbce00081633f4b5c4a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7-GCC/Clang-extract_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2f588485ad4f9e91064bd2593da752b75beb271b"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "006dc07dbfcd59a57647d8a9a5cc357f324c9484b74f83d928e1c9beea935e58"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7-GCC/Clang-extract_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
