[[Clang]]
arch = "x86_64"
git-tree-sha1 = "303e77a7766ea8616b5abe32251fcbecc131379d"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "ce537eb4be46c7df3bd8bf70faa53de5d0af049c5a1aa418c69277b95ed4a52c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "b3e48b142964d5b8dd04d09d9d0b1fc243d7413c"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "5166ef51a6e9c6ef70bc534396b54ab600eac1d4bad5d86d723a7c74780f5407"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "85c69b331427c72575c02ac39d9650ddf54a67fa"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "1044de4451f43ceb9adf0a36d0afc6dbc13509226a83f23b3d55996865edcba7"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bb4646b4457754a49e8e75054b9014384a83d78"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "e04167e1ba320da1cd326f06a8c137af6438317964132a5cba70e8a1124b8567"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang]]
arch = "powerpc64le"
git-tree-sha1 = "b3d99ce362452f1ec709a09d89be7279e7f3d880"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "e4a32f4703c6a9d59b8c896005b96fadfe4c869bfcd34f3062a21bc6908650f2"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "b47fc96af74076a20f6fd8ff9c283ed122e3f1d0"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "ebb7f9a50165da91065bf554134206b05053971e144c787f8f0873c9d25228d8"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "a185da36e829a66a2f0b62f77736af359f319a91"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "9493f7c5ebd72b1c1db04bdcdf1462f6a0b4e9518816562f0b422696f01d85f7"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "4e1a415983ec031b053e98c3ac8a9e7775d594f4"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "dfa7a0571c808dd8c34b765e2fef21bba071b537bcb7c3a68de67d27ea1812bf"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02ae7be7b5e15e4fe1b51c54f3d41c39f29584fa"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "fa912de788e90c66e944dfbc42ec61cf244d11488311cd2cbf9879f9454dbeb9"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2bcc58e2f10b42b254e9deefc4f9bf220c66ef3"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "9678c2051e58952771b1f87b56e6d6af0ab93f25d96dcc64b694a73d31124a09"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "1b0e779ed1f5c1f85bd5ab3c87dadbf595b85055"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "9345f697c41b2d1d97e3897c8d0c56c41c0020804ae54425dd0dc535e6466605"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "fa9cfedca1b8aa39a4e500cfbab110a095f5367e"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "4d7b131eb2d35a3c2521409dc041da5b0807b2f076369cb962d3679817e508ff"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "e2592fff4a9dd53538915aea4fbbc72855e34297"
os = "macos"
os_version = "14"
target = "any"

    [[Clang.download]]
    sha256 = "0345b0b88e127e973a704e92cc0f35bce12112afa40da02777b3a47571256baf"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "322349404b41d24f9288677d90c07e6e51d7acf8"
os = "macos"
os_version = "20"
target = "any"

    [[Clang.download]]
    sha256 = "20b1437d8741cd5e9c49634f70ccca7cdb02354205d63b6f0f8d49de15d1633c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "eacf4a5cde50d9a1c9241634c80b785faf30c16d"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "456fb8839a6f359721a20808029d7028cae7b4948d50f5f145e54b0407ff41d0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "b6ae2d95c5a34b8bb39b5a0f793996d3940d3dbe"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "3c02586dd0c4297f74c1890a58b70d5c7561790708fb96e52990915f7399d438"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "d2983b5fa2776c29ee6bec1da3917f26099aa400"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "30e1af0583680026967b7fd8d0b867d11ba918f9743d02820bef8e718d427fb9"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7fc2b6527146d09969212d4bfdf11a683ef5242c"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "b33ea82b10857b742621129019c68461240c5502256f9f08eed71f9563c8ca24"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "9404aa9e5b4b60cb68b6fbcc02607f48ddd32a7c"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "232270dd0cce5d9b2c8272546d7a09665a5df08d554da304a4914bdf59a9d111"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "ead536d7aa08a2f092bf641500806ec5d70f08da"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "2620c3503ce4de944b8c560a1b49d126e690509ae1ef352f3b32491d2042136b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "35f852bb604c42287c160a7a94ff4e8aeb7b6b07"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "578f8568451b17c23b8865dfdbeb08a3d99547f50dd523725573d6f3167fc68a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "282ecee253f22a6c25529ff08caff22b3a74542f"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "9213063aaa6b5389d15bf50d17764443fc32bc5d5cafd226ca4c1d4e28361850"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05b82bdcbba817c758401930550352242877d996"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d78eab177cac4102f70dc4318c7dff82194bc114e49ed9f950a948abd73beb35"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1728a366fafc5d0f9b97a19a0b9f537d3d2823a"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "64dc18fb4bb423264a3d7c6d58586585e64c675cce331efa9706b43e78cfa3f5"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "ece705f7afeeff2b6a37340c8984086a46a161a5"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "dac6876bce70c90cb5d78dff86d8fb55efb224d407cde318655d8ff0ca1d07ac"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "8c6b661517c950b7a02ac2259312a14b95bb6bd2"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "f7495041bbca20c22edf2f01d7fbe8a81f71b06805649d29ba520b465c1f3105"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "78c44a09b35cc02d837192a36d7a6035deab3802"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "4c9aa9160bae62033428766ef0bbeff37ea30ef16cea75b6d41515d640c633e3"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "50fabc14d005f3ea6a6bec1a7da3d0f894bbac14"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "55c5fa6e15c7c9cd8ccf6473b3fbc833f78f6b1475e9d9ea8be78f0be4c9f0d5"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "63e3ed88bc3a3d0983b0439cb7603b406bdd5941"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "c8d32b14dc66935d444334e3b4cff6bed0d49bc792ce19d2a79f38fda918ff26"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "eca0da919f59fabf25ecc6064bb79605e1c5fbfc"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "fc12481d5743ef0c474b428b1a16815126a195a25cbac0c621ee092bc127f261"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b0c03e89353cfc4c7dfd67d3d0aa014045a70498"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "eb71d2ceac25fe39d66baa9067206b8106529306e3a96ae08747c35571fa2972"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e61239bc7e2a86e6a9ca1df58deb63266b78fbd2"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "2aa8c75afcec738d1f0d92976eb8e46e28659516ab5303679508cc69b5446446"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "f2afaea15b470b49347e28ab777fd69b285ec01f"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "99736b804da33793afac688f633e88cea9a4d026a1aa2ad100ded202a0cd7875"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "aa41cf4a165ec83c4c897c3a7ee882e8ea63b68d"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "a4dddaa9a545b4f16aa1537d1e69917f5992835bd0ddee7b2625ef350fefcd5b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "74c079c4491d36f19018e2e6b22539701f0ee6fb"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "c66ae10086e56103709f82e1d3db3d0c9d86d589923e09e53a8330534da64fbb"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "6c71e5fc02fcd4d8f6239a2733b81c64f1667b31"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "d9f7660e6e52be1a375c1fde9daae158dbe2e777996ac7271823ffb8bf6ca501"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93b8a58ca9e06ac7126347e8a4b10d9a046f4457"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "db1c62d851ce5f8772f91714336edb448288525eabc79bf316517b407d091206"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce094581b0fee12e6a9b48c8ece5ad71d556a9dc"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "26830eba35b10a7adde91c9b3f62d2494e8ce5877385a43a9af0ef971073d39b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "db115ae4cf5de299add6be18cb755f5cd9390c2a"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "af828f6136e9c8162641c1b49664519adca6d10aaf8e8f7dd36a470c2beb5347"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "cf254cf56aab7bca1143508cfdc537c7eadfd2c8"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "631233aa9d173acd5e190eacab367d05cf663d9a393282e58046563d45f79ac7"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "77c6e536de86849974bb0b51f067f4f8b8ee19d5"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "d0fdae63767438a6d5310ca7cfb88322b89311a46997903d5f8f73a5f90722ff"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "907c7d5d8e4d1f865313dabc2b2bb57df128bfc9"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "fc7031ec198e1497d8eec05c7f58c086036959083a90f1da9ba34fe9d72d4b09"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"
