[[Clang]]
arch = "x86_64"
git-tree-sha1 = "0aeae368a7ceeac43c4d160d8659f4ffde4a217d"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "9af276683f0cd99b2eeeba6e698c098c8c247e236872e8342f491f9ffe1fb24c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "91253ae347f28304a462fd8063d104c3931f8574"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "cbda4ae7ae09868de1ee5287e97a7a8f9d3e8d670c5ff3326b08018a502f82e2"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "77b7c47e8dfcb58868002eb316c0ff93482dc2b3"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "093ac9439cbb7b7c0b1803aba992dd98aab6f48abf58d1eaee93edb1a2b6bd43"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7a619ec060443fd819b628aaa9949a4f8a1be10"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "31301aa1c7ac782bedf41e8000e46fe3b5384019f84b32fe37adf907a1b04c8e"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang]]
arch = "powerpc64le"
git-tree-sha1 = "24a6d0f8b4d888a1aaf721c024c60559d201c897"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "fd0d1eac723711f6e64925edfc72f48927c2259d86ff6dfd1a0f86d1a35d0798"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "7bfb6077141dfd16748dd8dd9f8ec260a112ff17"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "ff7c684519400d62d11af56f217c998b90fc0878ca0f4983524437f4f9f067b6"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "b528ab9b5862663bddccc86dda604c6f5cda444a"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "cbc167fe577fae873808ea369e914845f5aea93688b8427f0170d1bc0f301bca"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "df626a14b45aac7f5726a0f3c3f1c7aec34d7b87"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "b75723bc23da35de4c6385f14092c5c26430f136b04f9971af22b31510a2de95"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29b889d61ba6b88f5a717408e7384b9fd72357dc"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "befd91818e5ef3ddad58b6ddd604efc06162f8706cbe1363014ef25f8283cd09"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b8a325f925d1740b4519222929b4e8ca2fe74cf"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "bd5dfc47f1535db4c636fe40fcb2a2e10dfd35604131e393b3c222d48288a0ba"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "8fe42f943f08fc078535b347b37c7607118baa4d"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "66c4ed8099f93fb9002b45462a08eb1bb29c1c6877c9f69aed0d3e0d1e002783"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "97f4fbe26018e902fc56db6a47f502f013b9468b"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "c79ce1a7d4c7762d92447238e078f0298d05aa152ed04cd3a42b99e6515af6a1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-w64-mingw32-target+any.tar.gz"

[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "b1c522a203307f1eb48c921fc4e0422c03acca2a"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "589665ba612f15ac849651ef6e94aa30b7cd1f357801fa46c2e4b6c8592ad3e7"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "2ebbb8aeae777978a2bc0352dec6f3f35c0eb852"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "6490e29e6cbed43548acc5db765c348ef19e0998529227d4d012073d07b6396d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "d8b97f75c01b90512796f092789f83e7c64b21e7"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "c92266fd98b6ddff874f4471577bc0a1a065fd64f5b56da74eb16ac35e7f27f0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c97cd6ac1ac6a1ac47da5441456d5a86d98883bb"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "2f6843b8aa5dea7a665da6f1289f5da95c82e19b8276c9562d46a3a413165508"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "f76a028cda3e44393b2b4645e236305bd4ca1d30"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "9a8214c2e5cd059ee3e0193cda938252f3e04636270baaec50ae4ef364e565ca"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "bf8172b149551d194ccb74e10b230560d5d8c005"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "243cb672537412ce190b1e1508051cf66e6421568b98f3ee36c569ca7360d4b6"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "357e285c92a20173ef4b0469059f4517afb951bc"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "a556921f2cef6d90b4580575ff21f3e41b2b05fe9a677ab24c131c06e314ad80"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "e95e054835ad383fd9902102b6f04443554c2718"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "0a552c96250ca02cdc1cf2907d0e3f5b6b98d120a5b81d5a8323ab8e9b75b220"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bbe65c86f220ca53663f5c900c763800aad8c28"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "cda0377f0d5d2e8486730916536007f27a43f0566297ef9c8270a0ead2e62beb"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6afc7996ea0b79195bf53803940403954467eb90"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "7a43bd92ee3bedc5abd60d011a3978e8587e1552d029fa9504813e51784f2e88"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "4c9286d278acb2d69b46bfc9d9133ee6afb8889c"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "f3810f2ef2bf41f664ac8c440377b1637ae4860628d50baece4485c287ac9d4b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "7434232d81bd5253a63c79a4a413eb139c876aa7"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "86797d05ca843f73788d35c5acb6bf254b6fc2a29ab4d657dd9da19448d61b46"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"

[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4ba341519df89ded27f60d54abcbbd3725937751"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "c12a518097d4e9679e2764fa781079fece2ee69ce4893412c7b3d0c17dd15397"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "e5a48c1a7c4b6293c5da88ab34218aa354abd471"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "2704cb8739bc7a1431a8b52de84f1e7a50e88134cde3ae71066b83eb990ede31"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "56b03c5577f0651dc46f4ab0ad83d0be962eafd2"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "d97286766250152e40995cb6501b6f0fa0b90fdadcd4b8e2a2f2f07799784a26"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1f128a009d14db2e853e534fb0f49f9c2cd9306"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "e9a4a0abc14919772179f6f6474928df30f720add73e13ffb6ccd39cd1f0c93b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "753f3d07d39c6a31ab1e99ce4948e9a6f763074e"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "741e45611e4eb84f0b82619de0da98e286924b271865be81c409966902ee14c2"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8736ce8d21b0e8eb7558e7e81c15d18b8d9cf0ac"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "4f1507b8acfc84e08c98f51d8abb213c97d21a94271841a39294550b4dc95a2c"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "787effbae4190f3e347cea20b8f7e8309806088b"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "66c5997e1170e3d0829ccd37773f2c9b9d8a094a5cb57a15e921b1ac62d1ae29"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "9b9bb5639284dd88462e7c7e29ddea09f6967014"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "b0299deae62576593a00fa34a4a71eea989a99da4c63e04fd9a8de7c8fb8177b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a69179655de6d9111490dd54fed6d6591dfdc87"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "f1f90466199415ae9b8cc40c327cdb58b60fa867f4099743e2c6531137248599"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "28fa1c240ea9c7105d5b662f7f49493c15a09df6"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "f577485804f057506f72d866223a74492afa5b980b20ad3a5af1fe42b5b88704"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "148466866b0a3a06c78683e9a0bfb67febe31d30"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "612a3db95ebc2c486758c947e408066eb335b39f1f2934831a1a1a68301b3446"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "4a6f672520e148886c8f1eefcaf2d2f27ec3acc3"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "ee85665506ebbb6913a5971e62e05995c7d7373f01a5f7961158bb8c20d35f27"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
