[[Clang]]
arch = "x86_64"
git-tree-sha1 = "303e77a7766ea8616b5abe32251fcbecc131379d"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "7af9ee27d3bb31635f58f9e311adfaba9a8322aa96c41fa3b865828bbe941757"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "b3e48b142964d5b8dd04d09d9d0b1fc243d7413c"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "06315d83da5fefafd7ce6f3cda920021ce5f99b3cb65b8d4302cc1e7b430d632"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "85c69b331427c72575c02ac39d9650ddf54a67fa"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "1d995dcd0aa70544938aaaeeb3941bcac884f8258d619599d699c3a61b9e89eb"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bb4646b4457754a49e8e75054b9014384a83d78"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "ac8eaf7eca175086be61e2f3f1148d768ac16d71f09d943456f3c7dc9c626eae"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang]]
arch = "powerpc64le"
git-tree-sha1 = "b3d99ce362452f1ec709a09d89be7279e7f3d880"
libc = "glibc"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "3c9acb94bedf66ac6de2c3d02ef426eb77000f3b2351de9acab06f9846b139a6"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "b47fc96af74076a20f6fd8ff9c283ed122e3f1d0"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "f0478ee8d86038970fcea179b5a9e359606a2dd7ba45fd9e1232786c05147984"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "a185da36e829a66a2f0b62f77736af359f319a91"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "d7af42577d3e5856b58a0f04a754bebcda41876cf57fb36eeb0b512d5d245c13"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "4e1a415983ec031b053e98c3ac8a9e7775d594f4"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "1623d2f34d2a2d9760bb3ada9a181ab5405511dd94e81166b3564314ce6cf770"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02ae7be7b5e15e4fe1b51c54f3d41c39f29584fa"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "fb63151f970ec05ae730f6351e0b950ab0ded7e45457a8fc92ce287f7a7673ba"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2bcc58e2f10b42b254e9deefc4f9bf220c66ef3"
libc = "musl"
os = "linux"
target = "any"

    [[Clang.download]]
    sha256 = "6a00a5277981d03e3208d3f764bb5219cc411e53cc281299e1bb00814050ddbe"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "bb0ab1fd33c2fae03e3b8abd30eb2f6028c753b1"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "2d9e575ebd0602510bbad20f67e6b908a9be8f5b7e088f34f7de9f958aca3aa2"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "i686"
git-tree-sha1 = "74b23396cfbac5e1c55c9e512275bf13bd00757c"
os = "windows"
target = "any"

    [[Clang.download]]
    sha256 = "8944ec7cee7982d8703417f2f2b76b7a6adfafb4485873b11254ebeac2d2816e"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "e2592fff4a9dd53538915aea4fbbc72855e34297"
os = "macos"
os_version = "14"
target = "any"

    [[Clang.download]]
    sha256 = "d856af362fe2d86c51ab02bab80070ef4c82b9c22c1165cb37d1c286918d732a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "322349404b41d24f9288677d90c07e6e51d7acf8"
os = "macos"
os_version = "20"
target = "any"

    [[Clang.download]]
    sha256 = "5c47b405c2723c133e4c628b2d8ae74d84969479e8edb2ea370bb0eff4e0bc88"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "aeeb5e96297f443018c725e4e799d0654b887dbc"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "5da2b4c2f011ac619d0b787b165b11ecc40f08c824670ecd839c67cdabf36837"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "a6006c14fc007c842d45348889cab25081bed96d"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "88a55e8c7d9387a7b3302ea4a0649c2236b8c2c4eb05f0c85cbcaa407ceac25d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "c77f6c6d2c3c8298b39a95e984365f18977971f8"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "b356c41947d6b677b75795839c4a80f4608c3776861a0a89fc1cf65be3d06c87"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "908400a7626480e11176e8fab28112b68f5c51b1"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "388c9daa19bd4da938f6fea7754b18a1f61b10c831093c50a25206b0e042d08b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "239068450b765e185984c8b06d91d6d3df1bcbc4"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "d4a4986b427e659640d6c1f876fb4d3292a3eb38e9cf1017d8904fc94cf51f9d"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "089718a509245b6671e160021593f4732c02d11a"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "29471c62ddbf5c5275fac40771e095b060bacf3ce2600984e92cf7c9f68eeb8b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "d89649a8de1f9c2ab1b4974ad73051dc74a5909f"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "b7dec6ecba231fbd58d358918952746aa214f6f914cc5488b2bf2aa31de0eee0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "aeb6b71c9cc6a2d7d53c26dacc75d32c19ce22c9"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "3b9f133a90a233054ab2ab7118e0bad178cd568e2dc8bdb3cd09f6438415055f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f928f0233807289ac04a566a0987d86cdca73d23"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "43b98af14b01db27f9ae44ef13a1d22cf3532ed7ced93ba35aa8fc9d293a5de1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df8698fe0eac776dc2e4372081349e4161f9dec1"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "502e1602d6610633b6ab8f0001b81df0c2d4d3737ed9807645f797f7e2096e1f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "52f950191ce017c98f1b2c6d2e7f2822a954c0b2"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "3e46b7771b55f3084f0f658a2fb72be06911a00e6ddf9f5a701cec7f22bd8512"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "i686"
git-tree-sha1 = "27221fc65e1b012adad2b54b22c5ff2969f424db"
lazy = true
os = "windows"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "947e1a5a6e34d1e467ad370f83053a6b02c5431a3ee9d7bf8245157c7f298749"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "c25ceea3af32425bbed911ceea55645d2271f2a2"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "24593ac26cf7d985b04187f006ac3de238a8288153f6ed0be215f482dcffb2e1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "54e77966b1d7790cf74597c03cd45c84b80ce488"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-build_log.download]]
    sha256 = "2f70e432337f5d8820061719774e825432e33a086d7d532d63553e7ede03a99b"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-build_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"

[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d744ec72ad3cfdc1b9cb3e6a0f77658287e22698"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "515388acf8969906fab3f79b182f7ae8565d122966413ae83a2c4ea60a34b6c1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "e4d2d55c1fded30ba0ba48af42da0d0458b1522a"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "eb49fe5229fd4f51dbc7f610b096984c39ee75da764998952641694c067d27a7"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a322cf6c95ba3422b8aadbfdc3d2e1ec5baa74ce"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "15d62549c86c2df876649e6088e316cd0f3bf66ba415559369096cf64c3cf696"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3e6be41aac26abebb2cd09e87b689985604c061c"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "4b6b8a2a4dff9f8a21ec913fb5bd98d25e6b93258f2924bf34ec4dea1299208f"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-gnueabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "a96f4691348c255d0db4b4f2459c7d75c76aef6d"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "aa053df8ce4ba7c2843615a8777c7bb92d3e0e1c53be7e3a48ce20938bb2af45"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-powerpc64le-linux-gnu-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bd8db0595ce11e45622c2f76b55e92df35d83e19"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "565886bf0567bc054b6da90d3aeecbe9d30af5425f9812f386e71cca6987e413"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "37c1b6d6f1f81aa0ae4b5044ed3f7eaa8ffa517d"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "9c9906b070006627c77351d46f1012afb7e725a86f581d7ba95f9df217cde3a0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "4334c8934db7707e955b8ffecf9c3391c1283485"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "94ea0a1e52c4d9777cc8d019cc6af810bb013df242b0130a44a403655e2831f1"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-linux-musl-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75aaf1017851eb95899226c2bee5534400624cc8"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "2acc36eb6114cfaa6f8f84795258fc7eac6b4a3091a65a74fba88026c1500bc0"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv6l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "866200a60af4f2ac16e66f035eb5aa57c4698b16"
lazy = true
libc = "musl"
os = "linux"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "af292285d2be34ef198256dc4a266fb78febc77a7c374abf67d223d545f1cc24"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-armv7l-linux-musleabihf-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d75813e77000a10525f17b7f52013692c2f4c9aa"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "a9ab2efe427aea8641fc06b82e0881093d1507a8fcb0b2dc509c12b4acd2680a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "i686"
git-tree-sha1 = "653cac6ce1cac53eca5cddcc6318203c653bd280"
lazy = true
os = "windows"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "0a1e3d0e948de41d84476a7cce9c0c81f339e5c0a32cf770d634c89f66c95a91"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-i686-w64-mingw32-target+any.tar.gz"
[[Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c3a2c86949c87d1fc4c716757bf2e1f7f0a107c1"
lazy = true
os = "macos"
os_version = "14"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "dd98c362fbd75f390dac945907816fb87ffb838c7c2a2d05a73da0881b06676a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-x86_64-apple-darwin14-target+any.tar.gz"
[[Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a2501cbf91ce62b526eaed17fb76a1a0205041e5"
lazy = true
os = "macos"
os_version = "20"
target = "any"

    [[Clang-extract_log.download]]
    sha256 = "1a321609df705b551ef193698c05015bd8ffbd217a691959dffdd857bbdd1d7a"
    url = "https://github.com/staticfloat/Clang_jll.jl/releases/download/v17.0.7/Clang-extract_log-v17.0.7-aarch64-apple-darwin20-target+any.tar.gz"
